if(NOT Boost_FOUND)
    set(Boost_USE_STATIC_LIBS    OFF)
    set(Boost_USE_MULTITHREADED   ON)
    set(Boost_USE_STATIC_RUNTIME OFF)
    find_package(Boost 1.55.0 REQUIRED COMPONENTS python)
    message(STATUS "Boost_INCLUDE_DIRS         ${Boost_INCLUDE_DIRS}")
    message(STATUS "Boost_LIBRARIES            ${Boost_LIBRARIES}")
    message("")
endif()